import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH || '/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
const page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1,acceptDownloads:true});
const errors=[],remoteRequests=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
page.on('request',r=>{if(/^https?:/.test(r.url()))remoteRequests.push(r.url())});
await page.goto(new URL('../index.html', import.meta.url).href);
await page.waitForFunction(()=>!!window.__atlas?.renderer());
await page.waitForTimeout(1200);
assert.equal(await page.evaluate(()=>window.__atlas.model().group.visible),true);
assert.equal(await page.evaluate(()=>window.__atlas.scene().children.filter(x=>x.isGroup&&x.scale.x===15)[0].visible),false);
assert.equal(await page.locator('#finding-panel h2').innerText(),'Urinary bladder');
await page.screenshot({path:'preview-desktop.png',fullPage:true});
for(const [organ,label] of [['kidney','Left kidney'],['liver','Liver'],['hip','Left hip'],['bladder','Urinary bladder']]){
 await page.locator('.organ-chip[data-organ="'+organ+'"]').click();
 assert.equal(await page.locator('#finding-panel h2').innerText(),label);
 await page.locator('[data-action="effects"]').click();
 assert.equal(await page.locator('.effect-detail').count(),1);
 assert.equal(await page.locator('.effect-detail li').count(),3);
 await page.locator('[data-action="effects"]').click();
 assert.equal(await page.locator('.effect-detail').count(),0);
}
await page.locator('[data-action="reset"]').click();
await page.waitForTimeout(850);
await page.locator('[data-action="labels"]').click();
assert.equal(await page.locator('#anatomy-labels').isVisible(),false);
await page.locator('[data-action="labels"]').click();
await page.locator('[data-action="opacity"]').click();
await page.locator('#opacity').fill('35');
assert.equal(await page.evaluate(()=>window.__atlas.state.opacity),.35);
await page.locator('#opacity').fill('20');
await page.locator('[data-action="opacity"]').click();
await page.locator('[data-view="back"]').click();await page.waitForTimeout(750);
assert.equal(await page.locator('#side-r').innerText(),'L');
await page.locator('[data-view="front"]').click();await page.waitForTimeout(750);
const download=page.waitForEvent('download');await page.locator('[data-action="snapshot"]').click();await(await download).saveAs('Husam-3D-body.png');
await page.locator('.tab[data-tab="ct"]').click();await page.waitForTimeout(800);
assert.equal(await page.locator('#ct-preview').evaluate(img=>img.complete&&img.naturalWidth>0),true);
assert.equal(await page.evaluate(()=>window.__atlas.model().group.visible),false);
await page.locator('#ct-slice').fill('11');assert.equal(await page.locator('#slice-number').innerText(),'12 / 12');
await page.locator('[data-layer="bone"]').click();assert.equal(await page.locator('[data-layer="bone"]').getAttribute('class'),'active');
await page.locator('[data-layer="body"]').click();await page.locator('[data-layer="both"]').click();
await page.locator('#ct-slice').fill('6');await page.waitForTimeout(500);
await page.screenshot({path:'preview-ct.png',fullPage:true});
await page.locator('.tab[data-tab="sources"]').click();assert.equal(await page.locator('.source-card').count(),3);
const hrefs=await page.locator('.source-card a').evaluateAll(els=>els.map(e=>e.getAttribute('href')));assert.equal(hrefs.length,3);
await page.locator('.tab[data-tab="body"]').click();await page.locator('[data-action="language"]').click();
assert.equal(await page.locator('html').getAttribute('lang'),'ar');
assert.match(await page.locator('#finding-panel h2').innerText(),/المثانة/);
await page.waitForTimeout(600);await page.screenshot({path:'preview-arabic.png',fullPage:true});
await page.locator('[data-action="notes"]').click();assert.equal(await page.locator('.modal-backdrop [role="dialog"]').count(),1);await page.keyboard.press('Escape');assert.equal(await page.locator('.modal-backdrop [role="dialog"]').count(),0);
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(700);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.screenshot({path:'preview-mobile.png',fullPage:true});
await page.locator('.anatomy-label[data-organ="kidney"]').click();assert.match(await page.locator('#finding-panel h2').innerText(),/الكلية/);
await page.locator('.tab[data-tab="ct"]').click();await page.waitForTimeout(400);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
assert.deepEqual(errors,[]);assert.deepEqual(remoteRequests,[]);
await writeFile('tests/results.json',JSON.stringify({passed:true,tested:['Offline file launch','WebGL rendering','Initial CT hidden','All four organ selections','Effects explanations','Transparency','Label visibility','Front/back laterality','Image download','CT previews and surface controls','Source links','Arabic','Mobile layout and organ selection','No network requests','No browser errors'],browser:'Google Chrome',errors,remoteRequests},null,2));
console.log('PASS: 16 interaction, rendering, privacy and responsive checks.');
await browser.close();
