import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { createBodyModel } from './body-model.js';
import { createBladderDetail } from './bladder-detail.js';
import { createStudioStage } from './studio-stage.js';
import { findings } from './findings.js';
import { CT_BODY, CT_BONE } from '../assets/ct/geometry.js';
import ctMetadata from '../assets/ct/metadata.js';

import { createMotionController } from './motion-controller.js';

const root=document.querySelector('#app');
const state={lang:0,presentation:'anatomy',immersive:false,tour:-1,modelView:'body',layer:'lining',tab:'body',organ:'bladder',effects:false,labels:true,allLabels:false,toolsOpen:false,rotate:false,view:'front',opacity:0.2,ctLayer:'both',slice:6};
const T=(en,ar)=>state.lang?ar:en;
const L=value=>Array.isArray(value)?value[state.lang]:value;
const paths={expand:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5',chevron:'m9 5 7 7-7 7',spark:'m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5z',body:'M12 3a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-4 7 4-2 4 2 2 5m-12 0 2-5m2 3v5l-2 4m6-9v5l2 4',grid:'M3 3h7v7H3zm11 0h7v7h-7zM3 14h7v7H3zm11 0h7v7h-7z',scan:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M5 12h14m-7-7v14',file:'M14 2H5v20h14V7zm0 0v5h5M8 12h8m-8 4h6',note:'M5 3h14v18H5zM8 7h8M8 11h8m-8 4h5',arrow:'M7 17 17 7M7 7h10v10',download:'M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5',print:'M7 8V3h10v5M7 16H3V9h18v7h-4M7 13h10v8H7z',lock:'M7 10V7a5 5 0 0 1 10 0v3M5 10h14v11H5zm7 4v3',info:'M12 8v.01M12 11v6M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',plus:'M12 5v14M5 12h14',minus:'M5 12h14',rotate:'M20 7a9 9 0 1 0 1 8M20 3v5h-5',eye:'M2 12s3-7 10-7 10 7 10 7-3 7-10 7S2 12 2 12zm13 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0',layers:'m12 3 10 5-10 5L2 8zm-10 9 10 5 10-5M2 16l10 5 10-5',focus:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M9 12h6m-3-3v6',play:'m8 4 13 8-13 8z',pause:'M8 4v16M16 4v16',bladder:'M5 5C3 10 3 16 8 18l4 1 4-1c5-2 5-8 3-13M9 3l-1 4m7-4 1 4m-4 12v3',kidney:'M14 4c-5-5-13 2-11 9s10 10 13 4c2-4-4-4-5-7s5-3 3-6m1 8 4 2v8',liver:'M3 9c5-5 13-6 18-2l-1 7-7 2-3-4-7 5z',hip:'M5 3 3 10l5 4m11-11 2 7-5 4M8 9l4 3 4-3M7 13l-1 9m11-9 1 9m-7-9h2v5h-2z',check:'m5 12 4 4L19 6',close:'M5 5l14 14M5 19 19 5',heart:'M20 5c-4-4-8 1-8 1S8 1 4 5c-6 6 8 15 8 15S26 11 20 5',link:'M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-2 2m3 6a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l2-2'};
const icon=(name)=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.info}"/></svg>`;
const pdfLink=file=>`../${encodeURIComponent(file)}`;
let renderer,scene,camera,controls,model,detailModel,ctGroup,ctBody,ctBone,slicePlane,ground,studioStage;
let motion,labels=[],pointerStart=null,renderFailure=false,overlayAnimation=null,dialogReturnFocus=null;
let labelMetrics=new Map(),labelLinks=new Map(),lastStageSize="",refreshing=false;
const motionPreference=matchMedia('(prefers-reduced-motion: reduce)');
let prefersReduced=motionPreference.matches;

const tourSteps=[
 {organ:'bladder',view:'urinary',title:['Locate the bladder','تعرّف على موضع المثانة'],copy:['The body model shows the locations described by the CT before TURBT. Current residual disease is not established.','يوضح نموذج الجسم المواضع الواردة في التصوير قبل الاستئصال. لا تحدد الوثائق ما إذا كان هناك ورم متبقٍ حالياً.']},
 {organ:'bladder',view:'detail',title:['Look through the layers','استكشف طبقات الجدار'],copy:['Select a layer to connect the conceptual anatomy with the findings in the examined tissue sample.','اختر طبقة لربط التشريح التوضيحي بنتائج العينة النسيجية المفحوصة.']},
 {organ:'kidney',view:'urinary',title:['Understand kidney function','افهم وظيفة الكليتين'],copy:['A smaller left kidney and preserved contrast excretion are reported. These records do not measure an efficiency percentage.','وُصفت كلية يسرى أصغر مع إطراح محفوظ للمادة الظليلة. لا تقيس هذه الوثائق نسبة الكفاءة.']},
 {organ:'liver',view:'body',title:['Keep uncertainty visible','تعرّف على ما لم يُحسم'],copy:['The small liver findings remain indeterminate. The schematic markers are not confirmed metastases or exact CT locations.','تبقى بؤر الكبد الصغيرة غير محددة الطبيعة. العلامات توضيحية ولا تمثل نقائل مؤكدة أو مواقع دقيقة من التصوير.']},
 {organ:'hip',view:'body',title:['Put the hip in context','ضع ملاحظة الورك في سياقها'],copy:['The left-hip observation comes from the secondary Arabic review and needs specialist confirmation.','ملاحظة الورك الأيسر من المراجعة العربية الثانوية وتحتاج إلى تأكيد الاختصاصي.']}
];
const detailLayers={
 lining:{name:['Inner lining','البطانة الداخلية'],color:'#e6bc82',text:['The report assigns pTa: the primary tumor is described as non-invasive. The abstract growth symbol belongs to the lining; it does not reproduce the specimen’s inverted microscopic architecture.','يصنف التقرير الورم pTa ويصفه بأنه غير غازٍ. ترمز العلامة إلى ورم مرتبط بالبطانة؛ ولا تعيد بناء نمط العينة المقلوب مجهرياً.']},
 support:{name:['Supporting tissue','النسيج الداعم'],color:'#efd1ba',text:['No lamina propria invasion was identified in the examined specimen. This is a tissue-sample finding, not a measurement of every part of the bladder.','لم يُشاهد غزو للصفيحة الخاصة في العينة المفحوصة. هذه نتيجة تخص العينة وليست قياساً لكل أجزاء المثانة.']},
 muscle:{name:['Muscle wall','الجدار العضلي'],color:'#d0797b',text:['Detrusor muscle was present and tumor-free in the examined specimen. The enlarged cutaway makes the layer visible; its thickness is not a patient measurement.','عضلة المثانة موجودة وخالية من الورم في العينة المفحوصة. يُظهر المقطع المكبر هذه الطبقة؛ سُمكها ليس قياساً خاصاً بالمريض.']},
 lesion:{name:['Schematic growth','رمز الورم'],color:'#e6ae68',text:['A conceptual non-invasive growth symbol. It is not an exact tumor shape, residual-tumor claim, or microscopic reconstruction.','رمز توضيحي لنمو غير غازٍ. لا يمثل شكل الورم الدقيق أو وجود ورم متبقٍ أو إعادة بناء مجهرية.']}
};
function presentationSwitch(){return `<div class="presentation-switch" role="group" aria-label="${T('Anatomy layers','طبقات التشريح')}"><span>${T('ANATOMY LAYERS','طبقات التشريح')}</span>${[['anatomy','bladder','Organs','الأعضاء'],['muscles','body','Muscles','العضلات'],['skeleton','hip','Skeleton','الهيكل العظمي'],['skin','body','Skin','الجلد']].map(([id,ic,en,ar])=>`<button data-presentation="${id}" class="${state.presentation===id?'active':''}" aria-pressed="${state.presentation===id}">${icon(ic)}${T(en,ar)}</button>`).join('')}</div>`;}

function organRibbon(){return `<div class="organ-ribbon" role="group" aria-label="${T('Select an organ','اختر عضواً')}">${Object.entries(findings).map(([id,d],i)=>`<button class="organ-chip ${state.organ===id?'active':''}" data-organ="${id}" aria-pressed="${state.organ===id}"><span class="organ-icon">${icon(id)}</span><span class="organ-chip-copy"><strong>${L(d.short)}</strong><small>${L(d.status)}</small></span><span class="chip-index">0${i+1}</span></button>`).join('')}</div>`;}

function tourCard(){if(state.tour<0||state.tab!=='body')return '';const step=tourSteps[state.tour];return `<section class="tour-card" id="tour-card" aria-label="${T('Guided exploration','الاستكشاف الموجّه')}"><div class="tour-top"><span>${icon('spark')}${T('GUIDED EXPLORATION','استكشاف موجّه')}</span><button data-action="tour-close" aria-label="${T('Close guide','إغلاق الدليل')}">${icon('close')}</button></div><div class="tour-progress" aria-label="${T('Step','الخطوة')} ${state.tour+1} / ${tourSteps.length}">${tourSteps.map((_,i)=>`<i class="${i<=state.tour?'active':''}"></i>`).join('')}</div><div class="tour-step"><span>0${state.tour+1} / 0${tourSteps.length}</span><h3>${L(step.title)}</h3><p dir="${state.lang?'rtl':'ltr'}">${L(step.copy)}</p></div><div class="tour-navigation"><button data-action="tour-back" ${state.tour===0?'disabled':''}>${T('Previous','السابق')}</button><button data-action="tour-next">${state.tour===tourSteps.length-1?T('Finish tour','إنهاء الجولة'):T('Next step','الخطوة التالية')}${icon('chevron')}</button></div></section>`;}

function modelBar(){return `<div class="model-modebar" role="group" aria-label="${T('Anatomy view','عرض التشريح')}">${[['body','body','Whole body','كامل الجسم'],['urinary','kidney','Urinary focus','تركيز بولي'],['detail','layers','Bladder layers','طبقات المثانة']].map(([id,ic,en,ar])=>`<button data-scene="${id}" class="${state.modelView===id?'active':''}" aria-pressed="${state.modelView===id}">${icon(ic)}${T(en,ar)}</button>`).join('')}</div>`;}

function layerPanel(){const d=detailLayers[state.layer];return `<section class="layer-explainer"><span class="eyebrow">${T('LAYER BY LAYER','طبقة بعد طبقة')}</span><div class="layer-options">${Object.entries(detailLayers).filter(([id])=>id!=='lesion').map(([id,x])=>`<button data-wall="${id}" class="${state.layer===id?'active':''}"><i class="dot" style="color:${x.color}"></i>${L(x.name)}</button>`).join('')}</div><p>${L(d.text)}</p><small>${T('Pathology report · 9 Sep 2026 · p. 1','تقرير الأنسجة · 9 أيلول 2026 · ص 1')}</small></section>`;}

function ctPanel(){const p=ctMetadata.previews[state.slice];return `<div class="ct-image-card"><div class="ct-image-header"><span>${T('AXIAL PREVIEW','مقطع محوري')}</span><span id="slice-number">${state.slice+1} / 12</span></div><img id="ct-preview" src="./assets/ct/${p.file}" alt="${T('Original CT axial slice, unannotated','مقطع محوري أصلي غير معلّم')}"><input id="ct-slice" class="ct-slider" aria-label="${T('Browse CT slices','تصفح مقاطع التصوير')}" type="range" min="0" max="11" value="${state.slice}"><div class="ct-caption" id="ct-caption">${ctCaption()}</div></div>
 <div class="finding-card"><div class="card-top"><span class="card-index">${T('SOURCE STUDY','الدراسة الأصلية')}</span><span class="status">02 SEP 2026</span></div><h2>${T('Inside the scan','داخل التصوير')}</h2><p class="finding-diagnosis" style="margin-top:15px">${T('A reconstruction of Husam’s actual CT coverage: lower chest, abdomen, pelvis and upper thighs.','إعادة بناء لمنطقة الفحص الفعلية لحسام: أسفل الصدر والبطن والحوض وأعلى الفخذين.')}</p><div class="metric-grid"><div><span class="metric-label">${T('Selected series','السلسلة المحددة')}</span><span class="metric-value">98</span> <span class="metric-unit">${T('slices','مقطعاً')}</span></div><div><span class="metric-label">${T('Slice spacing','تباعد المقاطع')}</span><span class="metric-value">5</span> <span class="metric-unit">mm</span></div></div><h3 class="mini-title">${T('Surface layers','طبقات السطح')}</h3><div class="ct-layer-buttons">${['both','body','bone'].map(v=>`<button data-layer="${v}" class="${state.ctLayer===v?'active':''}">${v==='both'?T('Combined','معاً'):v==='body'?T('Body','الجسم'):T('Dense tissue','نسيج كثيف')}</button>`).join('')}</div><p class="function-note">${T('Dense tissue is extracted at 300 HU and can include structures other than bone. No tumor or organ segmentation was performed.','استُخرج النسيج الكثيف بعتبة 300 HU وقد يشمل تراكيب غير عظمية. لم تُحدد الأورام أو الأعضاء من الصور.')}</p><a class="source-link" href="./assets/ct/metadata.json" target="_blank" rel="noopener" style="margin-top:17px">${icon('file')}${T('View reconstruction provenance','عرض بيانات مصدر البناء')}${icon('arrow')}</a></div>
 <div class="info-card"><h3>${icon('info')}${T('Reading the preview','قراءة المقاطع')}</h3><p>${T('The slider moves through 12 sampled slices, from upper to lower anatomy. The line in the 3D view marks the slice height. Fixed soft-tissue window; illustrative, not a diagnostic DICOM viewer.','ينتقل الشريط بين 12 مقطعاً مختاراً من الأعلى للأسفل. يحدد الخط في النموذج مستوى المقطع. نافذة الأنسجة ثابتة وهذا عرض توضيحي وليس قارئ DICOM تشخيصياً.')}</p></div>`;}

function ctCaption(){const p=ctMetadata.previews[state.slice];return `${T('Series 2 · Instance','السلسلة 2 · صورة')} ${p.instanceNumber} · ${T('Patient right on image left','يمين المريض على يسار الصورة')}<br>WC 40 / WW 400 HU`;}

function sourcesView(){return `<div class="source-grid">${[
 ['Pathology report','تقرير الأنسجة','حسام صلاح مهدي.pdf','09 SEP 2026','The later tissue diagnosis: low-grade inverted urothelial carcinoma, pTa / G1. Collected 5 September; reported 9 September.','التشخيص النسيجي الأحدث: سرطان الظهارة البولية المقلوب منخفض الدرجة، pTa / G1. جُمعت العينة في 5 أيلول وصدر التقرير في 9 أيلول.'],
 ['Original CT report','تقرير التصوير الأصلي','report.pdf','03 SEP 2026','Describes the 2 September study: bladder masses before TURBT, kidney size and contrast excretion, and small indeterminate liver findings.','يصف فحص 2 أيلول: كتل المثانة قبل الاستئصال، حجم الكليتين وإطراح المادة الظليلة، وبؤر كبدية صغيرة غير محسومة.'],
 ['Arabic secondary review','المراجعة العربية الثانوية','مراجعة_عربية_لدراسة_البطن_والحوض.pdf','SECONDARY SOURCE','Additional commentary on the study, including left hip degeneration. It is a secondary review; the hip observation needs specialist confirmation.','تعليق إضافي على الدراسة يشمل تنكس الورك الأيسر. هذه مراجعة ثانوية وتحتاج ملاحظة الورك إلى تأكيد الاختصاصي.']
 ].map(s=>`<article class="source-card">${icon('file')}<span class="eyebrow">${s[3]}</span><h2>${T(s[0],s[1])}</h2><p>${T(s[4],s[5])}</p><a href="${pdfLink(s[2])}" target="_blank" rel="noopener">${T('Open original PDF','فتح ملف PDF الأصلي')} ↗</a></article>`).join('')}</div><div class="evidence-note"><strong>${T('How to read this atlas','كيف تقرأ هذا الأطلس')}</strong><br>${T('The body model combines a schematic of the earlier CT findings with the later pathology result. It is not a scan of Husam’s entire body and does not establish current tumor burden, complete removal, microscopic spread or an overall cancer stage. The separate CT view is derived from the supplied archive and preserves its actual scan coverage. No organ-efficiency percentages can be calculated from these files.','يجمع نموذج الجسم بين رسم توضيحي لنتائج التصوير السابقة ونتيجة الأنسجة الأحدث. ليس مسحاً لكامل جسم حسام ولا يثبت وجود ورم حالياً أو اكتمال الإزالة أو الانتشار المجهري أو المرحلة الكلية للسرطان. استُخرج عرض التصوير المنفصل من الأرشيف المرفق ويقتصر على منطقة الفحص الفعلية. لا يمكن حساب نسب كفاءة الأعضاء من هذه الملفات.')}</div><a class="reading-report-link" href="./research/index.html" target="_blank" rel="noopener">${icon('file')}${T('Read the research behind this design','اقرأ البحث الداعم لهذا التصميم')} ↗</a><h3 class="mini-title" style="margin-top:27px">${T('General medical references','مراجع طبية عامة')}</h3><div class="reference-list"><a href="https://www.cancer.gov/types/bladder/stages" target="_blank" rel="noopener">NCI · ${T('Bladder layers and staging','طبقات المثانة وتصنيفها')} ↗</a><a href="https://www.cancer.gov/types/bladder/symptoms" target="_blank" rel="noopener">NCI · ${T('Possible bladder symptoms','أعراض المثانة المحتملة')} ↗</a><a href="https://www.niddk.nih.gov/health-information/kidney-disease/kidneys-how-they-work" target="_blank" rel="noopener">NIDDK · ${T('Urinary anatomy','تشريح الجهاز البولي')} ↗</a><a href="https://www.niddk.nih.gov/health-information/professionals/clinical-tools-patient-management/kidney-disease/identify-manage-patients/evaluate-ckd" target="_blank" rel="noopener">NIDDK · ${T('Kidney function tests','فحوصات وظيفة الكلى')} ↗</a><a href="https://www.niams.nih.gov/health-topics/osteoarthritis" target="_blank" rel="noopener">NIAMS · ${T('Osteoarthritis','الفصال العظمي')} ↗</a></div>`;}

function timeline(){return `<div class="study-timeline"><div class="timeline-heading">${T('THE STUDY,','الدراسة،')}<br><strong>${T('IN CONTEXT','في سياقها')}</strong></div><div class="timeline-item"><b>02 ${T('SEP','أيلول')} 2026</b><span>${T('CT imaging · before TURBT','التصوير · قبل الاستئصال')}</span></div><div class="timeline-item"><b>05 ${T('SEP','أيلول')} 2026</b><span>${T('TURBT tissue collected','جمع عينة الاستئصال')}</span></div><div class="timeline-item"><b>09 ${T('SEP','أيلول')} 2026</b><span>${T('Pathology · pTa / G1','تقرير الأنسجة · pTa / G1')}</span></div></div>`;}

function showToast(message){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.role='status';el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),3400);}

function notes(){const wrapper=document.createElement('div');wrapper.className='modal-backdrop'+(state.lang?' ar-content':'');wrapper.dir=state.lang?'rtl':'ltr';wrapper.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><h2 id="modal-title">${T('Reading Husam’s atlas','فهم أطلس حسام')}</h2><p>${T('This atlas connects the reports to an illustrative body. The CT was obtained on 2 September, before TURBT tissue collection on 5 September. Pathology reported on 9 September gives the later tissue diagnosis. Lesions on the model represent the earlier CT description.','يربط هذا الأطلس التقارير بنموذج توضيحي للجسم. أُجري التصوير في 2 أيلول قبل جمع عينة الاستئصال في 5 أيلول. يقدم تقرير 9 أيلول التشخيص النسيجي الأحدث. تمثل الكتل على النموذج وصف التصوير السابق.')}</p><br><p>${T('The hip observation comes from the secondary Arabic review, while the bladder tissue result comes from the pathology report. Liver findings remain indeterminate. Organ performance cannot be given a percentage from these records.','ملاحظة الورك من المراجعة العربية الثانوية، ونتيجة نسيج المثانة من تقرير الأنسجة. تبقى بؤر الكبد غير محددة الطبيعة. لا يمكن إعطاء نسب لأداء الأعضاء من هذه الوثائق.')}</p><br><p>${T('Rotate the body, select an organ, and choose “Explore how it affects the body” for an explanation. Open “CT study” for the actual scan-derived surfaces and sampled slices. Everything runs locally without uploading the medical files.','دوّر الجسم واختر عضواً، ثم اختر «استكشف تأثيره على الجسم» للشرح. افتح «دراسة التصوير» لعرض الأسطح المشتقة من الفحص والمقاطع المختارة. يعمل العرض محلياً دون رفع الملفات الطبية.')}</p><button class="effect-btn" data-close>${T('Continue exploring','متابعة الاستكشاف')}</button></section>`;document.body.appendChild(wrapper);const before=document.activeElement;const close=()=>{wrapper.remove();document.removeEventListener('keydown',key);before?.focus();};const key=e=>{if(e.key==='Escape')close();if(e.key==='Tab'){e.preventDefault();wrapper.querySelector('button').focus();}};wrapper.querySelector('[data-close]').onclick=close;wrapper.onclick=e=>{if(e.target===wrapper)close();};document.addEventListener('keydown',key);wrapper.querySelector('button').focus();}

function snapshot(){
 if(!renderer||state.tab==='sources'){showToast(T('Open the body map or CT view to save a 3D image.','افتح خريطة الجسم أو عرض التصوير لحفظ صورة.'));return;}
 motion?.finishTransition();clearSceneTransition();updateLabels();renderer.render(scene,camera);
 const canvas=document.createElement('canvas'),source=renderer.domElement;
 canvas.width=Math.max(source.width,900);
 const scale=canvas.width/source.width, imageHeight=source.height*scale;
 const lines=state.tab==='ct'?[
  'CT study: 2 Sep 2026. Series 2: lower chest through upper thighs.',
  'Threshold-derived body and dense-tissue surfaces. No tumor or organ segmentation.',
  'Dense tissue can include non-bone structures. Educational reconstruction only.'
 ]:[
  'Selected: '+findings[state.organ].label[0]+' | '+findings[state.organ].status[0]+'.',
  'Bladder: low-grade inverted urothelial carcinoma, pTa / G1; pathology 9 Sep 2026.',
  'In examined sample: no lamina propria invasion identified; muscle present and tumor-free.',
  state.modelView==='detail'?'Conceptual wall cutaway; growth is symbolic, not patient tumor geometry or microscopic histology.':state.presentation!=='anatomy'?'General '+state.presentation+' layer: schematic anatomy, not patient-specific tissue findings.':'Masses illustrate CT before TURBT. Whether tumor remains now is not established.',
  'Liver findings: indeterminate. Left hip: secondary review; specialist confirmation needed.',
  'Left kidney: smaller; contrast excretion preserved. Organ efficiency is not measured.',
  'Schematic anatomy and locations; not patient organ segmentation.'
 ];
 const fontSize=Math.max(16,canvas.width/65), lineHeight=fontSize*1.5;
 const scratch=canvas.getContext('2d');scratch.font=fontSize+'px Arial';
 const wrapped=[];for(const line of lines){let current='';for(const word of line.split(' ')){const next=current?current+' '+word:word;if(scratch.measureText(next).width>canvas.width-50&&current){wrapped.push(current);current=word;}else current=next;}wrapped.push(current);}
 canvas.height=imageHeight+100+wrapped.length*lineHeight;
 const c=canvas.getContext('2d');c.fillStyle='#080f19';c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(source,0,55,canvas.width,imageHeight);
 c.fillStyle='#dae9df';c.font='24px Arial';c.fillText('HUSAM | '+(state.tab==='ct'?'CT reconstruction':'Body Atlas'),25,36);
 if(state.tab==='body'&&state.labels){const cssScale=canvas.width/source.clientWidth;c.save();c.translate(0,55);c.scale(cssScale,cssScale);c.strokeStyle='#8db4ac';c.lineWidth=1;document.querySelectorAll('.leader-lines path').forEach(p=>c.stroke(new Path2D(p.getAttribute('d'))));c.restore();c.font=(12*cssScale)+'px Arial';for(const el of labels){if(el.hidden||el.classList.contains('is-pin'))continue;const rect=el.getBoundingClientRect(),vp=source.getBoundingClientRect();const x=(rect.left-vp.left)*cssScale,y=(rect.top-vp.top)*cssScale+55;c.fillStyle='#19373c';c.fillRect(x,y,rect.width*cssScale,rect.height*cssScale);c.fillStyle='#dae9df';c.fillText(el.dataset.wall?detailLayers[el.dataset.wall].name[0]:findings[el.dataset.organ].short[0],x+8*cssScale,y+rect.height*cssScale*.66);}}
 if(document.querySelector('#side-r')&&!document.querySelector('#side-r').hidden){c.fillStyle='#a6c4c1';c.font='18px Arial';c.fillText(document.querySelector('#side-r').textContent,20,55+imageHeight/2);c.fillText(document.querySelector('#side-l').textContent,canvas.width-32,55+imageHeight/2);}
 c.fillStyle='#c3d7ce';c.font=fontSize+'px Arial';wrapped.forEach((line,i)=>c.fillText(line,25,imageHeight+83+i*lineHeight));
 const a=document.createElement('a');a.download='Husam-'+state.tab+'-'+state.organ+'.png';a.href=canvas.toDataURL('image/png');a.click();showToast(T('3D image saved with its medical context.','حُفظت الصورة مع سياقها الطبي.'));
}

function effectsContent(){const d=findings[state.organ];return `${state.effects?`<div class="effect-detail"><h3 class="mini-title">${T('How it works','كيف يحدث التأثير')}</h3>${state.organ==='bladder'?`<div class="bladder-wall" aria-label="Bladder wall schematic"><div class="wall-layer"><span>${T('Lining','البطانة')}</span><strong>pTa / G1</strong></div><div class="wall-layer"><span>${T('Supporting tissue','النسيج الداعم')}</span><span>${T('No invasion identified*','لا غزو مشاهد*')}</span></div><div class="wall-layer"><span>${T('Muscle','العضلة')}</span><span>${T('Tumor-free*','خالية من الورم*')}</span></div></div><p>${T('* In the examined tissue sample. Diagram is schematic.','* في العينة النسيجية المفحوصة. الرسم توضيحي.')}</p>`:''}<ol>${d.effects.map(e=>`<li>${L(e)}</li>`).join('')}</ol>${d.effectSource?`<a class="source-link" target="_blank" rel="noopener" href="${d.effectSource}">${T('General medical reference','مرجع طبي عام')} ${icon('arrow')}</a>`:''}<p>${T('Animation is explanatory. It does not measure flow or show current disease activity.','الحركة للتوضيح؛ لا تقيس التدفق ولا تُظهر نشاط المرض الحالي.')}</p></div>`:''}`;}

// Patch only the changing interface. The stage and its WebGL canvas stay mounted.
function patchHTML(element, html) {
 if(!element)return;
 const template=document.createElement('template');template.innerHTML=html;
 function reconcile(parent,incoming){
  const next=[...incoming.childNodes];
  next.forEach((node,i)=>{
   const current=parent.childNodes[i];
   if(!current){parent.appendChild(node.cloneNode(true));return;}
   if(current.nodeType!==node.nodeType||current.nodeName!==node.nodeName){current.replaceWith(node.cloneNode(true));return;}
   if(node.nodeType===Node.TEXT_NODE){if(current.nodeValue!==node.nodeValue)current.nodeValue=node.nodeValue;return;}
   if(node.nodeType!==Node.ELEMENT_NODE)return;
   for(const attr of [...current.attributes])if(!node.hasAttribute(attr.name)&&!(current.tagName==='DETAILS'&&attr.name==='open'))current.removeAttribute(attr.name);
   for(const attr of node.attributes)if(current.getAttribute(attr.name)!==attr.value)current.setAttribute(attr.name,attr.value);
   if(current instanceof HTMLInputElement&&current!==document.activeElement)current.value=node.value;
   reconcile(current,node);
  });
  while(parent.childNodes.length>next.length)parent.lastChild.remove();
 }
 reconcile(element,template.content);
}
function focusToken(){const el=document.activeElement;if(!el||!root.contains(el))return null;for(const name of ['action','organ','scene','presentation','wall','view','tab','layer'])if(el.dataset[name])return {name,value:el.dataset[name],type:el.classList.contains('anatomy-label')?'label':el.classList.contains('organ-chip')?'chip':'control',element:el};return el.id?{id:el.id,element:el}:null;}
function restoreFocus(token){if(!token||document.activeElement===token.element&&token.element.isConnected)return;let candidate;if(token.id)candidate=document.getElementById(token.id);else {const prefix=token.type==='label'?'.anatomy-label':token.type==='chip'?'.organ-chip':'';candidate=root.querySelector(`${prefix}[data-${token.name}="${CSS.escape(token.value)}"]`);}if(candidate&&!candidate.closest('[hidden]'))candidate.focus({preventScroll:true});}
function metricValue(value){const text=L(value);return `<bdi dir="${/[\u0600-\u06ff]/.test(String(text))?'rtl':'ltr'}">${text}</bdi>`;}
function findingPanel(){const d=findings[state.organ];return `<article class="finding-card ${state.effects?'has-effects':''}">
 <section class="finding-summary" aria-labelledby="finding-title"><div class="card-top"><span class="card-index">${T('SELECTED FINDING','النتيجة المحددة')}</span><span class="status"><i class="dot"></i>${L(d.status)}</span></div>
 ${state.modelView!=='detail'&&state.presentation!=='anatomy'?`<p class="layer-notice">${T('General anatomy layer. Select Organs to locate the report findings.','طبقة تشريحية عامة. اختر الأعضاء لعرض مواضع نتائج التقارير.')}</p>`:''}
 <h2 id="finding-title">${L(d.label)}</h2><div class="finding-ar" dir="${state.lang?'ltr':'rtl'}">${d.label[state.lang?0:1]}</div>
 <p class="finding-diagnosis">${L(d.diagnosis)}</p><p class="summary-context">${L(d.contextText)}</p>
 <div class="metric-grid">${d.metrics.map(m=>`<div><span class="metric-label">${L(m[0])}</span><span class="metric-value">${metricValue(m[1])}</span> <span class="metric-unit">${metricValue(m[2])}</span></div>`).join('')}</div>
 <a class="source-link" href="${pdfLink(d.sourceFile)}" target="_blank" rel="noopener">${icon('file')}${L(d.source)} ${icon('arrow')}</a>
 <div class="summary-actions"><button class="effect-btn" data-action="effects" aria-expanded="${state.effects}">${icon(state.effects?'pause':'play')}${state.effects?T('Hide effects explanation','إخفاء شرح التأثير'):T('Explore the effects','استكشف التأثيرات')}</button><button class="outline-btn mobile-details" data-action="details-open">${icon('file')}${T('Finding details','تفاصيل النتيجة')}</button></div></section>
 <div class="finding-extra" id="finding-extra">${state.modelView==='detail'?layerPanel():''}${effectsContent()}
 <details class="accordion"><summary>${T('What the records show','ما توضحه الوثائق')}</summary><ul class="finding-list">${d.points.map(x=>`<li><span class="checkmark">·</span><span>${L(x)}</span></li>`).join('')}</ul></details>
 <details class="accordion"><summary>${T('Function in context','الوظيفة في سياقها')}</summary><div class="function-row"><span>${L(d.functionLabel)}</span><span>${L(d.functionStatus)}</span></div><p class="function-note">${L(d.functionNote)}</p></details>
 </div></article>`;}
function topbar(){return `<a class="brand" href="#" data-tab="body" aria-label="Husam Body Atlas home"><span class="brand-symbol">${icon('body')}</span><span class="brand-name">body<span>atlas.</span></span></a><span class="top-label">${T('Husam Salah · Personal anatomy atlas','حسام صلاح مهدي · الأطلس التشريحي الشخصي')}</span><div class="top-actions"><span class="pill">${icon('lock')}${T('Local & private','محلي وخاص')}</span><button class="outline-btn" data-action="notes" aria-label="${T('Reading this atlas','فهم هذا الأطلس')}" title="${T('Reading this atlas','فهم هذا الأطلس')}">${icon('info')}</button><button class="language" data-action="language">${state.lang?'English':'العربية'}</button></div>`;}
function heading(){return `<div><h1>${state.tab==='body'?T('Husam’s <span class="hero-accent">anatomy.</span>','<span class="hero-accent">تشريح</span> حسام.'):state.tab==='ct'?T('Inside the CT study.','داخل دراسة التصوير.'):T('Reports & context.','التقارير والسياق.')}</h1><p class="subtitle">${T('Reported findings · 2–9 September 2026','النتائج الواردة في الوثائق · 2–9 أيلول 2026')}</p></div><div class="heading-actions studio-actions"><button class="tour-launch outline-btn" data-action="tour-start" aria-label="${T('Start guided tour','ابدأ جولة موجّهة')}" title="${T('Guided tour','جولة موجّهة')}">${icon('spark')}<span>${T('Guided tour','جولة موجّهة')}</span></button><button class="outline-btn" data-action="snapshot" aria-label="${T('Save labeled 3D image','حفظ صورة ثلاثية الأبعاد معنونة')}" title="${T('Save image','حفظ الصورة')}">${icon('download')}<span class="export-label">${T('Save image','حفظ الصورة')}</span></button><button class="outline-btn" data-action="print" aria-label="${T('Print this view','طباعة العرض')}" title="${T('Print','طباعة')}">${icon('print')}</button></div>`;}
function tabs(){return `<nav class="tabs" aria-label="${T('Atlas views','عروض الأطلس')}">${[['body','body','Body map','خريطة الجسم'],['ct','scan','CT study','دراسة التصوير'],['sources','file','Reports','التقارير']].map(([id,ic,en,ar])=>`<button class="tab ${state.tab===id?'active':''}" data-tab="${id}" aria-current="${state.tab===id?'page':'false'}">${icon(ic)}${T(en,ar)}</button>`).join('')}</nav>${state.tab==='body'?organRibbon():''}`;}
function viewerHeader(){const ct=state.tab==='ct';return `<div class="viewer-top"><div><div class="viewer-title">${ct?T('CT RECONSTRUCTION','إعادة بناء التصوير'):state.modelView==='detail'?T('BLADDER WALL','جدار المثانة'):T('ANATOMICAL EXPLORER','المستكشف التشريحي')}</div><div class="viewer-subtitle">${ct?T('Actual study · 02 Sep 2026 · Series 2','الدراسة الأصلية · 02 أيلول 2026 · السلسلة 2'):state.modelView==='detail'?T('Conceptual wall layers · examined tissue context','طبقات توضيحية · سياق العينة المفحوصة'):state.presentation==='anatomy'?T('Schematic anatomy · report-linked findings','تشريح توضيحي · نتائج مرتبطة بالتقارير'):T('General anatomy · illustrative model','تشريح عام · نموذج توضيحي')}</div></div><div class="viewer-top-actions"><span class="live-badge">${T('INTERACTIVE 3D','ثلاثي الأبعاد تفاعلي')}</span><button class="immersive-toggle view-tool" data-action="immersive" aria-pressed="${state.immersive}" aria-label="${state.immersive?T('Exit immersive view','خروج من العرض الموسع'):T('Immersive view','عرض موسع')}" title="${state.immersive?T('Exit immersive view','خروج من العرض الموسع'):T('Immersive view','عرض موسع')}">${icon(state.immersive?'close':'expand')}</button></div></div>${!ct?modelBar():''}${!ct&&state.modelView==='body'?presentationSwitch():''}`;}
function disclaimer(){return state.tab==='ct'?T('CT-derived threshold surfaces within the scanned region; no tumor or organ segmentation.','أسطح بعتبات كثافة ضمن منطقة التصوير؛ دون تحديد منفصل للأورام أو الأعضاء.'):state.modelView==='detail'?T('Conceptual layers; symbolic growth. Tissue findings apply to the examined sample.','طبقات توضيحية ونمو رمزي. نتائج الأنسجة تخص العينة المفحوصة.'):state.presentation!=='anatomy'?T('General educational anatomy. These layers are not patient-specific reconstructions.','تشريح تعليمي عام. هذه الطبقات ليست إعادة بناء خاصة بالمريض.'):T('Masses illustrate the CT before TURBT; current residual tumor is not established.','تمثل الكتل التصوير قبل الاستئصال؛ وجود ورم متبقٍ حالياً غير محسوم.');}
function toolButton(action,ic,en,ar,extra=''){return `<button class="view-tool ${extra}" data-action="${action}" aria-label="${T(en,ar)}" title="${T(en,ar)}">${icon(ic)}</button>`;}
function viewerFooter(){const clinical=state.tab==='body'&&(state.presentation==='anatomy'||state.modelView==='detail');return `<div class="model-disclaimer">${disclaimer()}</div><div class="viewer-bottom"><div class="view-controls"><div class="view-presets" role="group" aria-label="${T('Camera view','اتجاه العرض')}">${['front','back','side'].map(v=>`<button data-view="${v}" class="${state.view===v?'active':''}">${v==='front'?T('Front','أمام'):v==='back'?T('Back','خلف'):T('Side','جانب')}</button>`).join('')}${toolButton('reset','focus','Reset view','إعادة العرض')}</div><div class="view-tools ${state.toolsOpen?'tools-open':''}"><button class="view-tool ${state.rotate?'active':''}" data-action="rotate" aria-label="${T('Auto rotate','دوران تلقائي')}" aria-pressed="${state.rotate}" title="${prefersReduced?T('Reduced motion is enabled','تقليل الحركة مفعّل'):T('Auto rotate','دوران تلقائي')}" ${prefersReduced?'disabled':''}>${icon('rotate')}</button><button class="view-tool tools-toggle ${state.toolsOpen?'active':''}" data-action="tools" aria-label="${T('More viewing tools','أدوات عرض إضافية')}" aria-expanded="${state.toolsOpen}">${icon('layers')}</button>${toolButton('zoom-in','plus','Zoom in','تكبير','tool-secondary')}${toolButton('zoom-out','minus','Zoom out','تصغير','tool-secondary')}${toolButton('focus','focus',clinical?'Focus selected region':'Center view',clinical?'تركيز المنطقة المحددة':'توسيط العرض','tool-secondary')}${clinical?`<button class="view-tool tool-secondary ${state.labels?'active':''}" data-action="labels" aria-label="${T('Toggle organ labels','إظهار أسماء الأعضاء')}" title="${T('Toggle labels','إظهار الأسماء')}" aria-pressed="${state.labels}">${icon('eye')}</button><button class="view-tool tool-secondary all-labels-toggle ${state.allLabels?'active':''}" data-action="all-labels" aria-pressed="${state.allLabels}" title="${T('Show all labels','إظهار جميع الأسماء')}">${T('All labels','كل الأسماء')}</button>${state.modelView!=='detail'?toolButton('opacity','layers','Body transparency','شفافية الجسم','tool-secondary'):''}`:''}</div></div></div>`;}
function mountShell(){root.innerHTML=`<header class="topbar" id="topbar"></header><main class="main"><div class="page-heading" id="page-heading"></div><div class="workspace-nav" id="workspace-nav"></div><div class="workspace" id="workspace"><section class="viewer-card" id="viewer-card"><div class="viewer-header" id="viewer-header"></div><div class="stage-area" id="stage-area" dir="ltr"><div class="viewport" id="viewport"></div><div class="anatomy-labels" id="anatomy-labels"></div><span class="laterality left" id="side-r">R</span><span class="laterality right" id="side-l">L</span><div class="toolbar-slider hidden" id="opacity-popover"><label id="opacity-label" for="opacity"></label><input id="opacity" type="range" min="0" max="60" value="20"></div></div><div class="viewer-footer" id="viewer-footer"></div></section><aside class="panel" id="finding-panel"></aside></div><section id="sources-view" hidden></section><div id="timeline"></div><footer class="footer" id="footer"></footer></main><dialog class="details-dialog" id="details-dialog" aria-labelledby="details-title"><div class="dialog-header"><h2 id="details-title"></h2><button class="outline-btn" data-action="details-close"></button></div><div class="dialog-content" id="dialog-content"></div></dialog>`;
 const dialog=document.querySelector('#details-dialog');dialog.addEventListener('close',restoreDetails);dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
 document.querySelector('#finding-panel').addEventListener('toggle',()=>motion?.requestRender(),true);
}
function renderUI({animatePanel=false}={}){
 if(refreshing)return;refreshing=true;const focus=focusToken();if(!document.querySelector('#workspace'))mountShell();
 document.documentElement.lang=state.lang?'ar':'en';document.documentElement.dir=state.lang?'rtl':'ltr';root.dir=state.lang?'rtl':'ltr';root.className=[state.lang?'ar-content':'',state.immersive?'immersive-mode':''].filter(Boolean).join(' ');
 patchHTML(document.querySelector('#topbar'),topbar());patchHTML(document.querySelector('#page-heading'),heading());patchHTML(document.querySelector('#workspace-nav'),tabs());patchHTML(document.querySelector('#viewer-header'),viewerHeader());patchHTML(document.querySelector('#viewer-footer'),viewerFooter());
 document.querySelector('#workspace').hidden=state.tab==='sources';document.querySelector('#workspace').className=state.tab==='ct'?'workspace ct-layout':'workspace';document.querySelector('#sources-view').hidden=state.tab!=='sources';if(state.tab==='sources')patchHTML(document.querySelector('#sources-view'),sourcesView());
 patchHTML(document.querySelector('#timeline'),timeline());patchHTML(document.querySelector('#footer'),`<span>${T('Educational anatomy for discussion with the treating clinician.','تشريح تعليمي للمناقشة مع الطبيب المعالج.')}</span><span>${T('Drag to rotate · Scroll to zoom','اسحب للدوران · مرّر للتكبير')}</span>`);
 document.querySelector('#opacity-label').textContent=T('Body shell','غلاف الجسم');document.querySelector('#opacity').setAttribute('aria-label',T('Body shell opacity','عتامة غلاف الجسم'));document.querySelector('#opacity').value=state.opacity*100;
 updateFindingPanel(animatePanel);if(model){model.setFocus(state.organ);updateSceneVisibility();model.setEffects(state.effects);detailModel.setEffects(state.effects);controls.autoRotate=state.rotate&&!prefersReduced;updateCTLayers();createLabels();resize();motion?.requestRender();}
 document.querySelector('canvas')?.setAttribute('aria-label',T('Interactive 3D anatomy. Use arrow keys to rotate, plus or minus to zoom, Home to reset.','تشريح تفاعلي ثلاثي الأبعاد. استخدم الأسهم للدوران وإشارتي الجمع والطرح للتكبير والتصغير وزر Home لإعادة العرض.'));
 restoreFocus(focus);refreshing=false;
}
function updateFindingPanel(animate=false){const focus=focusToken(),dialog=document.querySelector('#details-dialog'),open=dialog?.open;
 if(open){const extra=dialog.querySelector('.finding-extra');if(extra)document.querySelector('#finding-panel .finding-card')?.append(extra);}
 patchHTML(document.querySelector('#finding-panel'),tourCard()+(state.tab==='ct'?ctPanel():findingPanel()));
 if(open&&state.tab==='body')populateDialog();else if(open)dialog.close();
 if(animate&&!prefersReduced){const panel=document.querySelector(open?'#dialog-content':'#finding-panel .finding-summary');panel?.getAnimations().forEach(a=>a.cancel());panel?.animate([{opacity:.45,transform:'translateY(6px)'},{opacity:1,transform:'translateY(0)'}],{duration:180,easing:'ease-out'});}
 restoreFocus(focus);
}
function populateDialog(){const d=findings[state.organ],dialog=document.querySelector('#details-dialog');dialog.dir=state.lang?'rtl':'ltr';document.querySelector('#details-title').textContent=L(d.label);const close=dialog.querySelector('[data-action="details-close"]');close.innerHTML=icon('close');close.setAttribute('aria-label',T('Close finding details','إغلاق تفاصيل النتيجة'));
 const content=document.querySelector('#dialog-content'),extra=document.querySelector('#finding-extra');content.replaceChildren();const context=document.createElement('div');context.className='dialog-context';context.innerHTML=`<span class="status">${L(d.status)}</span><p>${L(d.diagnosis)}</p><p>${L(d.contextText)}</p><a class="source-link" href="${pdfLink(d.sourceFile)}" target="_blank" rel="noopener">${L(d.source)} ↗</a>`;content.append(context);if(extra)content.append(extra);}
function openDetails(){if(state.tab!=='body')return;const dialog=document.querySelector('#details-dialog');if(dialog.open)return;dialogReturnFocus=document.activeElement;populateDialog();dialog.showModal();dialog.querySelector('[data-action="details-close"]').focus();}
function restoreDetails(){const extra=document.querySelector('#dialog-content .finding-extra');if(extra)document.querySelector('#finding-panel .finding-card')?.append(extra);document.querySelector('#dialog-content')?.replaceChildren();if(dialogReturnFocus?.isConnected)dialogReturnFocus.focus({preventScroll:true});dialogReturnFocus=null;}
function closeDetails(){document.querySelector('#details-dialog')?.close();}
function clearSceneTransition(){overlayAnimation?.cancel();overlayAnimation=null;document.querySelector('.scene-transition')?.remove();document.querySelector('#stage-area')?.classList.remove('transitioning');}
function captureSceneTransition(){clearSceneTransition();if(prefersReduced||!renderer||state.tab==='sources')return;const stage=document.querySelector('#stage-area');const overlay=document.createElement('canvas');overlay.className='scene-transition';overlay.setAttribute('aria-hidden','true');overlay.width=renderer.domElement.width;overlay.height=renderer.domElement.height;overlay.getContext('2d').drawImage(renderer.domElement,0,0);stage.append(overlay);stage.classList.add('transitioning');}
function playSceneTransition(){const overlay=document.querySelector('.scene-transition');if(!overlay)return;motion?.requestRender();overlayAnimation=overlay.animate([{opacity:1},{opacity:0}],{duration:220,easing:'ease-out',fill:'forwards'});overlayAnimation.finished.then(()=>{if(overlay===document.querySelector('.scene-transition')){clearSceneTransition();motion?.requestRender();}}).catch(()=>{});}
function setShellOpacity(){if(!model||state.presentation!=='anatomy')return;model.skinMaterials.forEach(m=>{m.opacity=m.userData.baseOpacity*(state.opacity/.2)*(state.modelView==='urinary'?.45:1);});motion?.requestRender();}
function updateSceneVisibility(){if(!model)return;const detail=state.tab==='body'&&state.modelView==='detail';model.group.visible=state.tab==='body'&&!detail;detailModel.group.visible=detail;ctGroup.visible=state.tab==='ct';ground.visible=false;studioStage.group.visible=false;if(model.getPresentation()!==state.presentation)model.setPresentation(state.presentation);setShellOpacity();detailModel.setLayer(state.layer);}
function choosePresentation(p){if(!['anatomy','muscles','skeleton','skin'].includes(p))return;captureSceneTransition();state.presentation=p;state.modelView='body';state.tab='body';state.tour=-1;state.effects=false;state.rotate=false;renderUI({animatePanel:true});setView('front');playSceneTransition();}
function chooseScene(view){captureSceneTransition();state.presentation='anatomy';state.modelView=view;state.effects=false;state.rotate=false;if(view==='detail'||view==='urinary'&&!['bladder','kidney'].includes(state.organ))state.organ='bladder';renderUI({animatePanel:true});setView('front');playSceneTransition();}
function selectOrgan(id){if(!findings[id])return;const changed=state.tab!=='body'||state.modelView==='detail'||state.presentation!=='anatomy';if(changed)captureSceneTransition();state.presentation='anatomy';state.organ=id;state.tab='body';if(state.modelView==='detail')state.modelView='body';state.effects=false;state.rotate=false;renderUI({animatePanel:true});focusSelected();if(changed)playSceneTransition();}
function goTour(index){if(index>=tourSteps.length){state.tour=-1;renderUI();showToast(T('You have explored all five perspectives.','استكشفت المناظير الخمسة.'));return;}captureSceneTransition();state.tour=Math.max(0,index);const step=tourSteps[state.tour];state.tab='body';state.presentation='anatomy';state.organ=step.organ;state.modelView=step.view;state.layer='lining';state.effects=false;state.rotate=false;renderUI({animatePanel:true});if(state.tour>2)focusSelected();else setView('front');playSceneTransition();}
function setImmersive(enabled){const focus=document.activeElement;state.immersive=enabled;root.classList.toggle('immersive-mode',enabled);patchHTML(document.querySelector('#viewer-header'),viewerHeader());resize({preserve:true});motion?.requestRender();if(enabled)document.querySelector('[data-action="immersive"]')?.focus({preventScroll:true});else if(focus?.isConnected)focus.focus({preventScroll:true});}

function initScene(){
 try{
  renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});
  renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x10242b,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
  renderer.domElement.setAttribute('aria-label','Interactive 3D anatomical model. Use organ buttons to explore findings.');renderer.domElement.tabIndex=0;
  scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(36,1,.01,100);camera.position.set(0,5.3,20);
  scene.add(new THREE.AmbientLight(0xcce7e3,.75));const key=new THREE.DirectionalLight(0xfff3e2,3.2);key.position.set(-5,10,8);scene.add(key);const rim=new THREE.DirectionalLight(0xd9e5ed,3.6);rim.position.set(5,7,-4);scene.add(rim);const fill=new THREE.DirectionalLight(0xead2bb,.9);fill.position.set(3,1,6);scene.add(fill);
  model=createBodyModel();scene.add(model.group);detailModel=createBladderDetail();scene.add(detailModel.group);detailModel.group.visible=false;model.setFocus(state.organ);model.setEffects(false);
  model.skinMaterials.forEach(m=>{m.userData.baseOpacity=m.opacity;});
  ctGroup=new THREE.Group();ctGroup.position.y=5;ctGroup.scale.setScalar(15);ctGroup.visible=false;scene.add(ctGroup);
  function mesh(data,material){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(data.positions,3));g.setAttribute('normal',new THREE.BufferAttribute(data.normals,3));g.setIndex(new THREE.BufferAttribute(data.indices,1));return new THREE.Mesh(g,material);}
  ctBody=mesh(CT_BODY,new THREE.MeshPhysicalMaterial({color:0x74b7b5,metalness:.12,roughness:.45,transparent:true,opacity:.16,depthWrite:false,side:THREE.DoubleSide}));ctBone=mesh(CT_BONE,new THREE.MeshStandardMaterial({color:0xd5d2b8,roughness:.65,metalness:.1}));ctGroup.add(ctBody,ctBone);
  const sliceGeo=new THREE.EdgesGeometry(new THREE.PlaneGeometry(.39,.34));slicePlane=new THREE.LineSegments(sliceGeo,new THREE.LineBasicMaterial({color:0xb0d6c2,transparent:true,opacity:.7}));slicePlane.rotation.x=-Math.PI/2;ctGroup.add(slicePlane);updateCTLayers();
  ground=new THREE.Group();ground.position.y=.04;scene.add(ground);for(const radius of [1.4,2,2.35]){const ring=new THREE.Mesh(new THREE.RingGeometry(radius-.012,radius,100),new THREE.MeshBasicMaterial({color:0x638f8d,transparent:true,opacity:radius===2?.28:.13,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ground.add(ring);}
  studioStage=createStudioStage();scene.add(studioStage.group);studioStage.setMode('body');studioStage.group.visible=false;ground.visible=false;
  controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,5,0);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=3;controls.maxDistance=35;controls.enablePan=true;controls.autoRotateSpeed=.8;controls.maxPolarAngle=Math.PI*.9;controls.minPolarAngle=Math.PI*.1;controls.addEventListener('start',()=>{clearSceneTransition();state.view='custom';state.rotate=false;controls.autoRotate=false;syncViewControls();});controls.update();
  renderer.domElement.addEventListener('pointerdown',e=>{clearSceneTransition();pointerStart={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('pointerup',e=>{if(!pointerStart||Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)>5||state.tab!=='body'||state.presentation!=='anatomy'&&state.modelView!=='detail')return;const rect=renderer.domElement.getBoundingClientRect();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const isDetail=state.modelView==='detail';const hit=ray.intersectObjects(isDetail?detailModel.group.children:model.organMeshes,true)[0];if(hit){let obj=hit.object;const field=isDetail?'layer':'organ';while(obj&&!obj.userData[field])obj=obj.parent;if(isDetail&&obj?.userData.layer&&detailLayers[obj.userData.layer]){state.layer=obj.userData.layer;detailModel.setLayer(state.layer);updateFindingPanel();}else if(!isDetail&&obj?.userData.organ){state.tour=-1;selectOrgan(obj.userData.organ);}}});
  renderer.domElement.addEventListener('keydown',e=>{
   if(['+','=','-','Home','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();clearSceneTransition();}
   if(e.key==='+'||e.key==='=')zoom(.85);if(e.key==='-')zoom(1.15);if(e.key==='Home')setView('front');
   if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){motion.cancelTransition();state.view='custom';state.rotate=false;controls.autoRotate=false;const sph=new THREE.Spherical().setFromVector3(camera.position.clone().sub(controls.target));if(e.key==='ArrowLeft')sph.theta-=.12;if(e.key==='ArrowRight')sph.theta+=.12;if(e.key==='ArrowUp')sph.phi-=.1;if(e.key==='ArrowDown')sph.phi+=.1;sph.phi=THREE.MathUtils.clamp(sph.phi,.2,Math.PI-.2);camera.position.copy(controls.target).add(new THREE.Vector3().setFromSpherical(sph));controls.update();syncViewControls();motion.requestRender();}
  });
  motion=createMotionController({camera,controls,isVisible:()=>!document.hidden&&state.tab!=='sources',canAnimate:()=>!prefersReduced,render:(time)=>{
   if(model.group.visible&&state.effects)model.update(prefersReduced?0:time/1000);
   if(detailModel.group.visible&&state.effects)detailModel.update(prefersReduced?0:time/1000);
   renderer.render(scene,camera);updateLabels();updateLaterality();
  }});
  motion.setReducedMotion(prefersReduced);motion.setContinuous(()=>state.effects&&state.tab==='body'&&!prefersReduced);
  document.querySelector('#viewport').appendChild(renderer.domElement);new ResizeObserver(()=>resize()).observe(document.querySelector('#stage-area'));resize();setView('front',true);createLabels();motion.requestRender();

 }catch(error){console.error(error);renderFailure=true;renderer=null;const vp=document.querySelector('#viewport');if(vp)vp.innerHTML=`<div class="viewer-fallback">${T('3D rendering is unavailable. Open in Chrome or Edge with hardware acceleration. Report details remain available.','العرض ثلاثي الأبعاد غير متاح. افتح الملف في Chrome أو Edge مع تسريع الرسوميات. تفاصيل التقارير متاحة.')}</div>`;}
}

function sceneBounds(){
 if(state.tab==='ct')return new THREE.Box3().setFromObject(ctGroup);
 if(state.modelView==='detail')return new THREE.Box3().setFromObject(detailModel.group);
 if(state.modelView==='urinary')return new THREE.Box3(new THREE.Vector3(-1.7,4,-.9),new THREE.Vector3(1.7,7.8,1));
 return new THREE.Box3(new THREE.Vector3(-2.1,.03,-.65),new THREE.Vector3(2.1,10.6,.85));
}
function fittedDistance(box){const size=box.getSize(new THREE.Vector3()),fov=THREE.MathUtils.degToRad(camera.fov);return THREE.MathUtils.clamp(Math.max(size.y/(2*Math.tan(fov/2)),size.x/(2*Math.tan(fov/2)*camera.aspect))*1.13+size.z/2,3,35);}
function resize({preserve=false}={}){const vp=document.querySelector('#viewport');if(!vp||!renderer)return;const w=vp.clientWidth,h=vp.clientHeight;if(!w||!h)return;const key=`${w}:${h}`;if(key===lastStageSize)return;lastStageSize=key;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();if(!preserve&&controls&&['front','back','side'].includes(state.view))setView(state.view,true);measureLabels();motion?.requestRender();}
function setView(view,instant=false){if(!camera)return;state.view=view;state.rotate=false;controls.autoRotate=false;const box=sceneBounds(),target=box.getCenter(new THREE.Vector3()),dist=fittedDistance(box);const offset=view==='back'?new THREE.Vector3(0,.2,-dist):view==='side'?new THREE.Vector3(dist,.2,0):new THREE.Vector3(state.modelView==='detail'&&state.tab==='body'?1.4:0,.2,dist);const pos=target.clone().add(offset);if(motion)motion.transitionCamera({target,position:pos,duration:instant?0:600});else{camera.position.copy(pos);controls.target.copy(target);controls.update();}syncViewControls();}
function syncViewControls(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));const b=document.querySelector('[data-action="rotate"]');if(b){b.classList.toggle('active',state.rotate);b.setAttribute('aria-pressed',String(state.rotate));}}
function zoom(factor){if(!motion)return;clearSceneTransition();state.view='custom';state.rotate=false;controls.autoRotate=false;const offset=camera.position.clone().sub(controls.target).multiplyScalar(factor).clampLength(3,35);motion.transitionCamera({target:controls.target,position:controls.target.clone().add(offset),duration:180});syncViewControls();}
function focusSelected(){if(!motion)return;if(state.tab==='body'&&state.modelView!=='detail'&&state.presentation!=='anatomy'){setView('front');return;}const target=state.tab==='ct'||state.modelView==='detail'?sceneBounds().getCenter(new THREE.Vector3()):model.anchors[state.organ].clone();const radius=state.tab==='ct'?3:state.modelView==='detail'?2.5:state.organ==='bladder'?1.25:1.6;const box=new THREE.Box3(target.clone().addScalar(-radius),target.clone().addScalar(radius));const distance=fittedDistance(box);state.view='custom';state.rotate=false;controls.autoRotate=false;motion.transitionCamera({target,position:target.clone().add(new THREE.Vector3(.3,.3,distance)),duration:600});syncViewControls();}
function updateCTLayers(){if(!ctBody)return;ctBody.visible=state.ctLayer!=='bone';ctBone.visible=state.ctLayer!=='body';ctBody.material.opacity=state.ctLayer==='body'?.65:.16;slicePlane.position.y=ctMetadata.previews[state.slice].positionFromCenterMeters;motion?.requestRender();}
function updateLaterality(){if(!camera)return;const offset=camera.position.clone().sub(controls.target);const sides=(state.tab==='ct'||state.modelView!=='detail')&&Math.abs(offset.z)>Math.abs(offset.x)*2;const r=document.querySelector('#side-r'),l=document.querySelector('#side-l');if(r){r.hidden=!sides;l.hidden=!sides;r.textContent=offset.z>=0?'R':'L';l.textContent=offset.z>=0?'L':'R';}}
function createLabels(){const holder=document.querySelector('#anatomy-labels');labels=[];labelLinks.clear();if(!holder)return;const clinical=state.tab==='body'&&(state.modelView==='detail'||state.presentation==='anatomy');holder.hidden=!state.labels||!clinical;if(!clinical){holder.replaceChildren();return;}const wall=state.modelView==='detail',entries=Object.entries(wall?detailLayers:findings);patchHTML(holder,`<svg class="leader-lines" aria-hidden="true">${entries.map(([id])=>`<path data-leader="${id}"/><circle data-point="${id}" r="2"/>`).join('')}</svg>${entries.map(([id,d],i)=>`<button class="anatomy-label ${wall?'wall-label':''} ${(wall?id===state.layer:id===state.organ)?'active':!state.allLabels&&!wall?'is-pin':''}" ${wall?'data-wall':'data-organ'}="${id}" aria-label="${L(wall?d.name:d.label)}" title="${L(wall?d.name:d.label)}" dir="auto"><i class="dot" style="color:${d.color}"></i><span class="label-text">${L(wall?d.name:d.short)}</span><span class="pin-number" aria-hidden="true">${i+1}</span></button>`).join('')}`);labels=[...holder.querySelectorAll('button')];labels.forEach(el=>{const id=el.dataset.wall||el.dataset.organ;labelLinks.set(id,{path:holder.querySelector(`[data-leader="${id}"]`),point:holder.querySelector(`[data-point="${id}"]`)});});measureLabels();motion?.requestRender();}
function measureLabels(){labelMetrics.clear();for(const el of labels){const was=el.hidden;el.hidden=false;labelMetrics.set(el,{width:el.offsetWidth||44,height:el.offsetHeight||44});el.hidden=was;}}
function updateLabels(){if(!renderer||state.tab!=='body'||!state.labels)return;const w=renderer.domElement.clientWidth,h=renderer.domElement.clientHeight;if(!w||!h)return;const boxes=[],ordered=[...labels].sort((a,b)=>Number(b.classList.contains('active'))-Number(a.classList.contains('active')));const intersects=(a,b)=>a.x<b.x+b.w+8&&a.x+a.w+8>b.x&&a.y<b.y+b.h+8&&a.y+a.h+8>b.y;
 const blockers=[{x:0,y:h/2-20,w:28,h:40},{x:w-28,y:h/2-20,w:28,h:40}];const pop=document.querySelector('#opacity-popover');if(pop&&!pop.classList.contains('hidden')){const p=pop.getBoundingClientRect(),r=renderer.domElement.getBoundingClientRect();blockers.push({x:p.left-r.left,y:p.top-r.top,w:p.width,h:p.height});}
 for(const el of ordered){const id=el.dataset.wall||el.dataset.organ,wall=!!el.dataset.wall,p=(wall?detailModel.anchors[id]:model.anchors[id]).clone().project(camera),rawX=(p.x*.5+.5)*w,rawY=(-p.y*.5+.5)*h,m=labelMetrics.get(el)||{width:44,height:44},pin=el.classList.contains('is-pin'),links=labelLinks.get(id);const offscreen=p.z>1||p.z< -1||rawX<0||rawX>w||rawY<0||rawY>h;el.hidden=offscreen;if(offscreen){links.path.setAttribute('d','');links.point.style.display='none';continue;}
  const left=['liver','support','muscle'].includes(id);const preferredX=pin?rawX-m.width/2:rawX+(left?-m.width-20:20),preferredY=rawY-m.height/2;let chosen=null;
  const xs=wall?[left?10:w-m.width-10,preferredX,10,w-m.width-10]:[preferredX,rawX+(left?20:-m.width-20),10,w-m.width-10];
  for(const dy of [0,-52,52,-104,104,-156,156]){for(const xx of xs){const box={x:Math.max(8,Math.min(w-m.width-8,xx)),y:Math.max(8,Math.min(h-m.height-8,preferredY+dy)),w:m.width,h:m.height};if(![...boxes,...blockers].some(b=>intersects(box,b))){chosen=box;break;}}if(chosen)break;}
  if(!chosen){el.hidden=true;links.path.setAttribute('d','');links.point.style.display='none';continue;}boxes.push(chosen);el.style.transform=`translate(${chosen.x}px,${chosen.y}px)`;const endX=THREE.MathUtils.clamp(rawX,chosen.x,chosen.x+chosen.w),endY=THREE.MathUtils.clamp(rawY,chosen.y,chosen.y+chosen.h);links.path.setAttribute('d',`M ${rawX} ${rawY} L ${endX} ${endY}`);links.point.style.display='';links.point.setAttribute('cx',rawX);links.point.setAttribute('cy',rawY);
 }
}
function switchTab(tab){if(state.tab===tab)return;closeDetails();captureSceneTransition();state.tab=tab;state.tour=-1;state.rotate=false;state.effects=false;state.immersive=false;renderUI();if(tab!=='sources'){setView('front',true);playSceneTransition();}else{clearSceneTransition();motion?.requestRender();}}
root.addEventListener('click',e=>{
 const button=e.target.closest('[data-action],[data-tab],[data-organ],[data-view],[data-layer],[data-scene],[data-wall],[data-presentation]');if(!button)return;
 if(button.dataset.tab){e.preventDefault();switchTab(button.dataset.tab);return;}
 if(button.dataset.organ){state.tour=-1;selectOrgan(button.dataset.organ);return;}
 if(button.dataset.presentation){choosePresentation(button.dataset.presentation);return;}
 if(button.dataset.scene){state.tour=-1;chooseScene(button.dataset.scene);return;}
 if(button.dataset.wall){state.layer=button.dataset.wall;detailModel.setLayer(state.layer);updateFindingPanel(true);createLabels();motion.requestRender();return;}
 if(button.dataset.view){clearSceneTransition();setView(button.dataset.view);return;}
 if(button.dataset.layer){state.ctLayer=button.dataset.layer;updateCTLayers();document.querySelectorAll('[data-layer]').forEach(b=>b.classList.toggle('active',b.dataset.layer===state.ctLayer));return;}
 switch(button.dataset.action){
  case 'immersive':setImmersive(!state.immersive);break;
  case 'tour-start':goTour(0);break;
  case 'tour-next':goTour(state.tour+1);break;
  case 'tour-back':goTour(state.tour-1);break;
  case 'tour-close':state.tour=-1;updateFindingPanel();break;
  case 'language':state.lang=1-state.lang;renderUI();break;
  case 'details-open':openDetails();break;
  case 'details-close':closeDetails();break;
  case 'effects':if(state.presentation!=='anatomy'){captureSceneTransition();state.presentation='anatomy';renderUI();playSceneTransition();}state.effects=!state.effects;model?.setEffects(state.effects);detailModel?.setEffects(state.effects);updateFindingPanel(true);if(state.effects)focusSelected();motion.requestRender();break;
  case 'rotate':if(prefersReduced)break;clearSceneTransition();motion.cancelTransition();state.rotate=!state.rotate;state.view='custom';controls.autoRotate=state.rotate;syncViewControls();motion.requestRender();break;
  case 'tools':state.toolsOpen=!state.toolsOpen;patchHTML(document.querySelector('#viewer-footer'),viewerFooter());resize({preserve:true});motion.requestRender();break;
  case 'labels':state.labels=!state.labels;createLabels();patchHTML(document.querySelector('#viewer-footer'),viewerFooter());motion.requestRender();break;
  case 'all-labels':state.allLabels=!state.allLabels;state.labels=true;createLabels();patchHTML(document.querySelector('#viewer-footer'),viewerFooter());motion.requestRender();break;
  case 'opacity':document.querySelector('#opacity-popover').classList.toggle('hidden');motion.requestRender();break;
  case 'zoom-in':zoom(.84);break;
  case 'zoom-out':zoom(1.18);break;
  case 'focus':clearSceneTransition();focusSelected();break;
  case 'reset':clearSceneTransition();setView('front');break;
  case 'notes':notes();break;
  case 'snapshot':snapshot();break;
  case 'print':closeDetails();window.print();break;
 }
});
root.addEventListener('input',e=>{
 if(e.target.id==='opacity'){state.opacity=Number(e.target.value)/100;setShellOpacity();}
 if(e.target.id==='ct-slice'){state.slice=Number(e.target.value);const p=ctMetadata.previews[state.slice];document.querySelector('#ct-preview').src=`./assets/ct/${p.file}`;document.querySelector('#slice-number').textContent=`${state.slice+1} / 12`;document.querySelector('#ct-caption').innerHTML=ctCaption();updateCTLayers();}
});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.immersive&&!document.querySelector('#details-dialog')?.open)setImmersive(false);});
motionPreference.addEventListener('change',e=>{prefersReduced=e.matches;if(prefersReduced){state.rotate=false;clearSceneTransition();root.getAnimations({subtree:true}).forEach(a=>{try{a.finish();}catch{a.cancel();}});}motion?.setReducedMotion(prefersReduced);model?.setEffects(state.effects);detailModel?.setEffects(state.effects);if(prefersReduced){model?.update(0);detailModel?.update(0);}patchHTML(document.querySelector('#viewer-footer'),viewerFooter());motion?.requestRender();});
window.addEventListener('resize',()=>{if(innerWidth>=1100)closeDetails();});
document.fonts.ready.then(()=>{measureLabels();motion?.requestRender();});
let printAccordions=[];
window.addEventListener('beforeprint',()=>{closeDetails();clearSceneTransition();motion?.finishTransition();printAccordions=[...document.querySelectorAll('.accordion')].map(el=>({el,open:el.open}));printAccordions.forEach(({el})=>el.open=true);motion?.requestRender();});
window.addEventListener('afterprint',()=>{printAccordions.forEach(({el,open})=>{if(el.isConnected)el.open=open;});printAccordions=[];motion?.requestRender();});
renderUI();initScene();
window.__atlas={state,scene:()=>scene,model:()=>model,detail:()=>detailModel,renderer:()=>renderer,ctMetadata,camera:()=>camera,stage:()=>studioStage,motion:()=>({...motion?.getState(),overlay:!!document.querySelector('.scene-transition')}),controls:()=>controls};
