export const findings = {
  bladder: {
    label: ['Urinary bladder','المثانة البولية'], short:['Bladder','المثانة'], status:['Pathology confirmed','مؤكد بتقرير الأنسجة'], color:'#e59779',
    sub:['Low-grade · pTa / G1','منخفض الدرجة · pTa / G1'],
    diagnosis:['Low-grade inverted urothelial carcinoma is reported in the TURBT specimen. The two illustrated masses represent the earlier CT, before tissue was collected.','يصف تقرير عينة الاستئصال سرطان الظهارة البولية المقلوب منخفض الدرجة. تمثل الكتلتان في الرسم وصف التصوير السابق لأخذ العينة.'],
    metrics:[[['Category, as reported','التصنيف كما ورد'],'pTa / G1',''],[['Pre-TURBT masses','كتل قبل الاستئصال'],'2',['on CT','بالتصوير']]],
    points:[['No lamina propria invasion identified in the sample.','لم يُشاهد غزو للصفيحة الخاصة في العينة.'],['Detrusor muscle is present and tumor-free in the sample.','عضلة المثانة موجودة في العينة وخالية من الورم.'],['CT: left 18 × 10 mm; right 13 × 8 mm.','التصوير: يسار 18 × 10 مم؛ يمين 13 × 8 مم.']],
    source:['Pathology · p. 1 + CT · p. 1','الأنسجة ص 1 + التصوير ص 1'], sourceFile:'حسام صلاح مهدي.pdf',
    context:['What this means','معنى النتيجة'], contextText:['The examined tissue supports a non-invasive finding. These records do not establish complete removal or whether a tumor remains today.','تدعم العينة المفحوصة وصفاً غير غازٍ. لا تثبت هذه الوثائق اكتمال الإزالة أو وجود ورم متبقٍ حالياً.'],
    functionLabel:['Storage & urine flow','تخزين البول وتصريفه'], functionStatus:['No dilatation on CT','لا توسع بالتّصوير'],
    functionNote:['CT reports no dilatation of the kidneys or ureters. Bladder capacity and current symptoms were not measured here.','لا يصف التصوير توسع الكليتين أو الحالبين. سعة المثانة والأعراض الحالية غير مقاسة هنا.'],
    effects:[['Kidneys make urine; ureters carry it into the bladder. The animation shows this general pathway.','تُنتج الكليتان البول وينقله الحالبان إلى المثانة. تُظهر الحركة هذا المسار العام.'],['The pre-procedure CT described growths inside the bladder near the ureter entrances.','وصف التصوير قبل الإجراء كتلتين داخل المثانة قرب فتحتي الحالبين.'],['Such growths can cause blood in urine, urgency or burning. Husam’s actual symptoms are not documented.','قد ترتبط هذه الأورام بدم في البول أو إلحاح أو حرقة؛ أعراض حسام الفعلية غير موثقة.']],
    effectSource:'https://www.cancer.gov/types/bladder/symptoms'
  },
  kidney: {
    label:['Left kidney','الكلية اليسرى'],short:['Left kidney','الكلية اليسرى'],status:['CT observation','نتيجة التصوير'],color:'#d4ba75',sub:['Smaller size · preserved excretion','حجم أصغر · إطراح محفوظ'],
    diagnosis:['The left kidney is smaller, with a lobulated contour and mildly thinner parenchyma. Both kidneys excreted contrast normally on the CT.','الكلية اليسرى أصغر حجماً مع سطح مفصص ونسيج أرق قليلاً. يذكر التصوير إطراحاً طبيعياً للمادة الظليلة من الكليتين.'],
    metrics:[[['Left kidney length','طول الكلية اليسرى'],'9.0','cm'],[['Right kidney length','طول الكلية اليمنى'],'11.8','cm']],
    points:[['No stones or focal kidney lesions reported.','لم تُذكر حصى أو آفات كلوية بؤرية.'],['No collecting-system or ureter dilatation reported.','لم يُذكر توسع الجهاز الجامع أو الحالبين.'],['The cause of the size difference is not established.','سبب اختلاف الحجم غير محسوم.']],
    source:['CT report · p. 1','تقرير التصوير · ص 1'],sourceFile:'report.pdf',context:['Size is not a function score','الحجم ليس مقياساً للكفاءة'],
    contextText:['A smaller kidney does not tell us its percentage function. Blood and urine tests are needed to assess filtration and kidney damage.','لا يُحدد صغر الكلية نسبة وظيفتها. يحتاج تقييم الترشيح والضرر الكلوي إلى فحوصات الدم والبول.'],
    functionLabel:['Contrast excretion','إطراح المادة الظليلة'],functionStatus:['Preserved on CT','محفوظ بالتّصوير'],functionNote:['No creatinine, eGFR or split renal-function result is supplied. An efficiency percentage cannot be calculated.','لم تُرفق نتائج الكرياتينين أو eGFR أو وظيفة كل كلية منفردة. لا يمكن حساب نسبة كفاءة.'],
    effects:[['Kidneys filter blood and make urine. The particles illustrate the direction of urine transport.','تُرشح الكليتان الدم وتُنتجان البول. توضح الجزيئات اتجاه انتقال البول.'],['The left kidney is drawn smaller to illustrate the reported difference in length.','رُسمت الكلية اليسرى أصغر لتوضيح فرق الطول الوارد في التقرير.'],['Preserved contrast excretion is an imaging observation, not a measurement of filtration capacity.','الإطراح المحفوظ ملاحظة تصويرية، وليس قياساً لقدرة الترشيح.']],effectSource:'https://www.niddk.nih.gov/health-information/professionals/clinical-tools-patient-management/kidney-disease/identify-manage-patients/evaluate-ckd'
  },
  liver: {
    label:['Liver','الكبد'],short:['Liver','الكبد'],status:['Indeterminate','غير محدد الطبيعة'],color:'#d4ba75',sub:['Small findings · not characterized','بؤر صغيرة · غير محسومة'],
    diagnosis:['A few small low-density liver findings are described. Their nature could not be confidently determined on the CT.','وُصفت بؤر كبدية صغيرة منخفضة الكثافة. لم يُحسم نوعها بثقة في التصوير المقطعي.'],
    metrics:[[['Largest reported focus','أكبر بؤرة مذكورة'],'7.7','mm'],[['Characterization','تحديد الطبيعة'],['Uncertain','غير محسوم'],'']],
    points:[['Small benign cysts are a possibility.','الأكياس الصغيرة الحميدة احتمال وارد.'],['The CT report could not confidently exclude metastases.','لم يتمكن تقرير التصوير من استبعاد النقائل بثقة.'],['These are not confirmed metastases or confirmed cysts.','هذه ليست نقائل مؤكدة ولا أكياساً مؤكدة.']],
    source:['CT report · pp. 1–2','تقرير التصوير · ص 1–2'],sourceFile:'report.pdf',context:['Keep uncertainty visible','الطبيعة ما زالت غير محسومة'],contextText:['The CT report suggests liver MRI or imaging follow-up as clinically appropriate. The illustrated marker locations are schematic.','يقترح تقرير التصوير رنيناً للكبد أو متابعة تصويرية حسب التقييم الطبي. مواقع العلامات في الرسم توضيحية.'],
    functionLabel:['Liver function','وظيفة الكبد'],functionStatus:['Not assessed here','غير مقاسة هنا'],functionNote:['These small imaging findings do not establish liver dysfunction. Liver-function laboratory results are not supplied.','لا تثبت هذه البؤر الصغيرة خللاً بوظيفة الكبد. لم تُرفق فحوصات وظائف الكبد.'],
    effects:[['Markers show the idea of small focal findings; they are enlarged for visibility and are not exact CT coordinates.','توضح العلامات فكرة البؤر الصغيرة؛ كُبرت للرؤية ولا تمثل إحداثيات دقيقة من التصوير.'],['The report cannot decide whether these represent small cysts or another process.','لا يحسم التقرير ما إذا كانت أكياساً صغيرة أو تغيراً آخر.'],['No effect on liver performance is established in the supplied records.','لم يُثبت تأثير على أداء الكبد في الوثائق المرفقة.']],effectSource:null
  },
  hip: {
    label:['Left hip','الورك الأيسر'],short:['Left hip','الورك الأيسر'],status:['Secondary review','مراجعة ثانوية'],color:'#d4ba75',sub:['Degenerative changes described','تغيرات تنكسية موصوفة'],
    diagnosis:['The Arabic secondary review describes moderate-to-severe chronic degenerative changes in the left hip. This observation is not in the original radiologist’s report.','تصف المراجعة العربية الثانوية تغيرات تنكسية مزمنة متوسطة إلى شديدة في الورك الأيسر. هذه الملاحظة غير واردة في تقرير اختصاصي الأشعة الأصلي.'],
    metrics:[[['Location','الموضع'],['Left hip','الورك الأيسر'],''],[['Evidence level','المصدر'],['Review','مراجعة'],'']],
    points:[['Joint-space narrowing and bony sclerosis described.','وُصف تضيق المسافة المفصلية وتصلب عظمي.'],['Subchondral cysts, osteophytes and mild remodeling described.','وُصفت كيسات تحت غضروفية ونابتات عظمية وإعادة تشكل خفيفة.'],['Needs confirmation by the treating specialist.','تحتاج إلى تأكيد من الاختصاصي المعالج.']],
    source:['Arabic secondary review · p. 1','المراجعة العربية الثانوية · ص 1'],sourceFile:'مراجعة_عربية_لدراسة_البطن_والحوض.pdf',context:['A separate musculoskeletal finding','ملاحظة مستقلة في الجهاز الحركي'],contextText:['The secondary review describes a degenerative pattern. This is not presented as spread from the bladder finding.','تصف المراجعة الثانوية نمطاً تنكسياً. لا يُعرض هذا بوصفه انتشاراً من ورم المثانة.'],
    functionLabel:['Movement & mobility','الحركة والتنقل'],functionStatus:['Symptoms unknown','الأعراض غير موثقة'],functionNote:['Pain, stiffness, walking ability and range of motion were not measured in these records.','لم يُقاس الألم أو التيبس أو القدرة على المشي أو مدى الحركة في هذه الوثائق.'],
    effects:[['The highlight locates the left hip joint, where the secondary review describes degenerative changes.','تحدد الإضاءة مفصل الورك الأيسر الذي تصف فيه المراجعة تغيرات تنكسية.'],['Degenerative joint changes may cause pain, stiffness and reduced movement.','قد تسبب التغيرات التنكسية ألماً وتيبساً ومحدودية في الحركة.'],['These possible effects are general education; the records do not establish Husam’s functional limitation.','هذه تأثيرات محتملة للتوضيح العام؛ لا تحدد الوثائق مقدار تأثر حركة حسام.']],effectSource:'https://www.niams.nih.gov/health-topics/osteoarthritis'
  }
};
