export const findings = {
  bladder: {
    label: ['Urinary bladder','المثانة البولية'], short:['Bladder','المثانة'], status:['Pathology confirmed','مؤكد بتقرير الأنسجة'], color:'#e59779',
    sub:['Low-grade · pTa / G1','منخفض الدرجة · pTa / G1'],
    diagnosis:['Low-grade inverted urothelial carcinoma is reported in the TURBT specimen. The two illustrated masses represent the earlier CT, before tissue was collected.','يصف تقرير عينة الاستئصال سرطان الظهارة البولية المقلوب منخفض الدرجة. تمثل الكتلتان في الرسم وصف التصوير السابق لأخذ العينة.'],
    metrics:[[['Category, as reported','التصنيف كما ورد'],'pTa / G1',''],[['Pre-TURBT masses','كتل قبل الاستئصال'],'2',['on CT','بالتصوير']]],
    points:[['No lamina propria invasion identified in the sample.','لم يُشاهد غزو للصفيحة الخاصة في العينة.'],['Detrusor muscle is present and tumor-free in the sample.','عضلة المثانة موجودة في العينة وخالية من الورم.'],['CT: left 18 × 10 mm; right 13 × 8 mm.','التصوير: يسار 18 × 10 مم؛ يمين 13 × 8 مم.']],
    source:['Pathology · p. 1 + CT · p. 1','الأنسجة ص 1 + التصوير ص 1'], sourceFile:'حسام صلاح مهدي.pdf',
    context:['What this means','معنى النتيجة'], contextText:['The examined tissue supports a non-invasive finding. These records do not establish complete removal or whether a tumor remains today.','تدعم العينة المفحوصة وصفاً غير غازٍ. لا تثبت هذه الوثائق اكتمال الإزالة أو وجود ورم متبقٍ حالياً.'],
    functionLabel:['Storage & urine flow','تخزين البول وتصريفه'], functionStatus:['No dilatation on CT','لا توسع بالتّصوير'],
    functionNote:['CT reports no dilatation of the kidneys or ureters. Bladder capacity and current symptoms were not measured here.','لا يصف التصوير توسع الكليتين أو الحالبين. سعة المثانة والأعراض الحالية غير مقاسة هنا.'],
    effects:[['Kidneys make urine; ureters carry it into the bladder. The animation shows this general pathway.','تُنتج الكليتان البول وينقله الحالبان إلى المثانة. تُظهر الحركة هذا المسار العام.'],['The pre-procedure CT described growths inside the bladder near the ureter entrances.','وصف التصوير قبل الإجراء كتلتين داخل المثانة قرب فتحتي الحالبين.'],['Such growths can cause blood in urine, urgency or burning. Husam’s actual symptoms are not documented.','قد ترتبط هذه الأورام بدم في البول أو إلحاح أو حرقة؛ أعراض حسام الفعلية غير موثقة.']],
    effectSource:'https://www.cancer.gov/types/bladder/symptoms'
  },
  kidney: {
    label:['Left kidney','الكلية اليسرى'],short:['Left kidney','الكلية اليسرى'],status:['CT observation','نتيجة التصوير'],color:'#d4ba75',sub:['Smaller size · preserved excretion','حجم أصغر · إطراح محفوظ'],
    diagnosis:['The left kidney is smaller, with a lobulated contour and mildly thinner parenchyma. Both kidneys excreted contrast normally on the CT.','الكلية اليسرى أصغر حجماً مع سطح مفصص ونسيج أرق قليلاً. يذكر التصوير إطراحاً طبيعياً للمادة الظليلة من الكليتين.'],
    metrics:[[['Left kidney length','طول الكلية اليسرى'],'9.0','cm'],[['Right kidney length','طول الكلية اليمنى'],'11.8','cm']],
    points:[['No stones or focal kidney lesions reported.','لم تُذكر حصى أو آفات كلوية بؤرية.'],['No collecting-system or ureter dilatation reported.','لم يُذكر توسع الجهاز الجامع أو الحالبين.'],['The cause of the size difference is not established.','سبب اختلاف الحجم غير محسوم.']],
    source:['CT report · p. 1','تقرير التصوير · ص 1'],sourceFile:'report.pdf',context:['Size is not a function score','الحجم ليس مقياساً للكفاءة'],
    contextText:['A smaller kidney does not tell us its percentage function. Blood and urine tests are needed to assess filtration and kidney damage.','لا يُحدد صغر الكلية نسبة وظيفتها. يحتاج تقييم الترشيح والضرر الكلوي إلى فحوصات الدم والبول.'],
    functionLabel:['Contrast excretion','إطراح المادة الظليلة'],functionStatus:['Preserved on CT','محفوظ بالتّصوير'],functionNote:['No creatinine, eGFR or split renal-function result is supplied. An efficiency percentage cannot be calculated.','لم تُرفق نتائج الكرياتينين أو eGFR أو وظيفة كل كلية منفردة. لا يمكن حساب نسبة كفاءة.'],
    effects:[['Kidneys filter blood and make urine. The particles illustrate the direction of urine transport.','تُرشح الكليتان الدم وتُنتجان البول. توضح الجزيئات اتجاه انتقال البول.'],['The left kidney is drawn smaller to illustrate the reported difference in length.','رُسمت الكلية اليسرى أصغر لتوضيح فرق الطول الوارد في التقرير.'],['Preserved contrast excretion is an imaging observation, not a measurement of filtration capacity.','الإطراح المحفوظ ملاحظة تصويرية، وليس قياساً لقدرة الترشيح.']],effectSource:'https://www.niddk.nih.gov/health-information/professionals/clinical-tools-patient-management/kidney-disease/identify-manage-patients/evaluate-ckd'
  },
  liver: {
    label:['Liver','الكبد'],short:['Liver','الكبد'],status:['MRI reviewed · indeterminate','رُوجع الرنين · الطبيعة غير محسومة'],color:'#d4ba75',sub:['Tiny focus · preliminary MRI review','بؤرة صغيرة جداً · مراجعة رنين أولية'],
    diagnosis:['The earlier CT described a few tiny liver findings. The 14 September MRI review identifies a possible fluid-containing focus in the posterior right liver, but does not confirm a cyst or characterize every earlier CT focus.','وصف التصوير السابق بؤراً كبدية صغيرة جداً. تحدد مراجعة رنين 14 سبتمبر بؤرة محتملة تحتوي على سائل في الجزء الخلفي من الفص الأيمن للكبد، لكنها لا تؤكد كيساً ولا تحسم طبيعة جميع بؤر التصوير السابق.'],
    metrics:[[['Largest focus on earlier CT','أكبر بؤرة بالتصوير السابق'],'7.7','mm'],[['MRI review target','موضع المراجعة بالرنين'],['Under 1 cm*','أقل من 1 سم*'],'']],
    points:[['*Approximate MRI appearance; an exact diameter and lesion count were not established.','*وصف تقريبي بالرنين؛ لم يُثبت قياس دقيق أو عدد كلي للآفات.'],['The MRI focus is bright on T2 and dark relative to enhanced liver on later T1 images; its identity needs radiologist confirmation.','تبدو البؤرة مرتفعة الإشارة على T2 ومنخفضة بالنسبة للكبد المعزز على صور T1 اللاحقة؛ وتحتاج طبيعتها إلى تأكيد اختصاصي الأشعة.'],['These remain unconfirmed findings: neither cysts nor metastases are established by the AI review.','تظل هذه ملاحظات غير مؤكدة؛ فلا تثبت مراجعة الذكاء الاصطناعي أكياساً أو نقائل.']],
    source:['Liver MRI · preliminary review, 14 September','رنين الكبد · مراجعة أولية، 14 سبتمبر'],sourceFile:'assets/reports/liver-mri-en-ar.pdf',context:['MRI completed; confirmation still needed','أُنجز الرنين؛ وما زال التأكيد مطلوباً'],contextText:['A preliminary review is available, with an image reference for one tiny right-liver focus. Obtain the signed MRI report and compare the full study with the earlier CT. Body-model markers remain schematic, not exact lesion coordinates.','تتوفر مراجعة أولية مع صورة مرجعية لبؤرة صغيرة جداً بالكبد الأيمن. يلزم الحصول على تقرير الرنين الموقّع ومقارنة الدراسة كاملة بالتصوير السابق. تبقى علامات مجسم الجسم توضيحية ولا تمثل إحداثيات دقيقة للآفات.'],
    functionLabel:['Liver function','وظيفة الكبد'],functionStatus:['Not assessed here','غير مقاسة هنا'],functionNote:['These small imaging findings do not establish liver dysfunction. Liver-function laboratory results are not supplied.','لا تثبت هذه البؤر الصغيرة خللاً بوظيفة الكبد. لم تُرفق فحوصات وظائف الكبد.'],
    effects:[['Markers illustrate small focal findings; their number and position do not constitute an MRI lesion map.','توضح العلامات بؤراً صغيرة؛ ولا يمثل عددها وموضعها خريطة لآفات الرنين.'],['The marked MRI reference is one unconfirmed review target, not proof that all earlier CT findings are benign.','الصورة المرجعية بالرنين تحدد موضع مراجعة واحداً غير مؤكد، ولا تثبت أن جميع بؤر التصوير السابق حميدة.'],['No effect on liver performance is established in the supplied records.','لم يُثبت تأثير على أداء الكبد في الوثائق المرفقة.']],effectSource:null
  },
  chest: {
    label:['Chest & lungs','الصدر والرئتان'],short:['Chest','الصدر'],status:['Preliminary AI review','مراجعة أولية بالذكاء الاصطناعي'],color:'#8cbcb0',sub:['No obvious major lung finding','لا تغير رئوي كبير واضح'],
    diagnosis:['The 13 September chest CT has a preliminary review showing no obvious lung mass, focal consolidation, pleural fluid or pneumothorax. This limited review needs radiologist confirmation and does not exclude small or subtle disease.','تتوفر مراجعة أولية لتصوير الصدر بتاريخ 13 سبتمبر دون كتلة رئوية واضحة أو تكثف بؤري أو سائل جنبي أو استرواح صدر. تحتاج المراجعة المحدودة إلى تأكيد اختصاصي الأشعة ولا تستبعد الأمراض الصغيرة أو الدقيقة.'],
    metrics:[[['CT study','تاريخ تصوير الصدر'],['13 Sep 2026','13 سبتمبر 2026'],''],[['Lung-nodule measurement','قياس عقدة رئوية'],['No confirmed target','لا موضع مؤكد للقياس'],'']],
    points:[['No convincing separate pulmonary nodule was identified to measure in this review.','لم تُحدد عقدة رئوية مستقلة واضحة بما يكفي لتأكيد وجودها وقياسها في هذه المراجعة.'],['IV contrast is present, but the study is not documented as a dedicated pulmonary angiogram; pulmonary embolism cannot be reliably excluded.','توجد صبغة وريدية، لكن الفحص غير موثق كتصوير مخصص للشرايين الرئوية؛ ولا يمكن استبعاد الانصمام الرئوي بشكل موثوق.'],['Tiny liver foci on the included upper-abdominal images remain incompletely characterized.','تظل البؤر الكبدية الصغيرة في صور أعلى البطن غير مكتملة التوصيف.']],
    source:['Chest CT · preliminary review, 14 September','تصوير الصدر · مراجعة أولية، 14 سبتمبر'],sourceFile:'assets/reports/chest-ct-en-ar.pdf',context:['A limited image review','مراجعة محدودة للصور'],contextText:['No signed chest report or symptom history was available. Compare the preliminary summary with the official report; no cancer clearance or automatic lung-nodule follow-up schedule is implied.','لم يتوفر تقرير صدر موقّع أو وصف للأعراض. ينبغي مقارنة الملخص الأولي بالتقرير الرسمي؛ ولا يعني ذلك نفي السرطان أو فرض جدول متابعة تلقائي لعقدة رئوية.'],
    functionLabel:['Breathing & lung function','التنفس ووظيفة الرئة'],functionStatus:['Not measured here','غير مقاسة هنا'],functionNote:['No spirometry, oxygen measurement or quantified lung-function result was supplied. The anatomical model cannot provide a lung-efficiency percentage.','لم تُقدَّم نتائج قياس التنفس أو الأكسجين أو وظيفة الرئة الكمية. لا يمكن للمجسم التشريحي تحديد نسبة كفاءة الرئتين.'],
    effects:[['The lung shapes locate the reviewed chest region; their appearance is illustrative anatomy, not patient-specific lung segmentation.','تحدد أشكال الرئتين منطقة الصدر المراجعة؛ وهي تشريح توضيحي وليست تقسيماً خاصاً برئتي المريض.'],['Any breathing animation is explanatory and does not measure this patient’s respiratory function.','أي حركة تنفسية هي للتوضيح ولا تقيس وظيفة التنفس لدى المريض.'],['Absence of an obvious CT finding in this review does not establish that new or worsening symptoms are harmless.','عدم ظهور خلل واضح بالتصوير في هذه المراجعة لا يثبت أن الأعراض الجديدة أو المتفاقمة غير خطرة.']],effectSource:null
  },
  hip: {
    label:['Left hip','الورك الأيسر'],short:['Left hip','الورك الأيسر'],status:['Secondary review','مراجعة ثانوية'],color:'#d4ba75',sub:['Degenerative changes described','تغيرات تنكسية موصوفة'],
    diagnosis:['The Arabic secondary review describes moderate-to-severe chronic degenerative changes in the left hip. This observation is not in the original radiologist’s report.','تصف المراجعة العربية الثانوية تغيرات تنكسية مزمنة متوسطة إلى شديدة في الورك الأيسر. هذه الملاحظة غير واردة في تقرير اختصاصي الأشعة الأصلي.'],
    metrics:[[['Location','الموضع'],['Left hip','الورك الأيسر'],''],[['Evidence level','المصدر'],['Review','مراجعة'],'']],
    points:[['Joint-space narrowing and bony sclerosis described.','وُصف تضيق المسافة المفصلية وتصلب عظمي.'],['Subchondral cysts, osteophytes and mild remodeling described.','وُصفت كيسات تحت غضروفية ونابتات عظمية وإعادة تشكل خفيفة.'],['Needs confirmation by the treating specialist.','تحتاج إلى تأكيد من الاختصاصي المعالج.']],
    source:['Arabic secondary review · p. 1','المراجعة العربية الثانوية · ص 1'],sourceFile:'مراجعة_عربية_لدراسة_البطن_والحوض.pdf',context:['A separate musculoskeletal finding','ملاحظة مستقلة في الجهاز الحركي'],contextText:['The secondary review describes a degenerative pattern. This is not presented as spread from the bladder finding.','تصف المراجعة الثانوية نمطاً تنكسياً. لا يُعرض هذا بوصفه انتشاراً من ورم المثانة.'],
    functionLabel:['Movement & mobility','الحركة والتنقل'],functionStatus:['Symptoms unknown','الأعراض غير موثقة'],functionNote:['Pain, stiffness, walking ability and range of motion were not measured in these records.','لم يُقاس الألم أو التيبس أو القدرة على المشي أو مدى الحركة في هذه الوثائق.'],
    effects:[['The highlight locates the left hip joint, where the secondary review describes degenerative changes.','تحدد الإضاءة مفصل الورك الأيسر الذي تصف فيه المراجعة تغيرات تنكسية.'],['Degenerative joint changes may cause pain, stiffness and reduced movement.','قد تسبب التغيرات التنكسية ألماً وتيبساً ومحدودية في الحركة.'],['These possible effects are general education; the records do not establish Husam’s functional limitation.','هذه تأثيرات محتملة للتوضيح العام؛ لا تحدد الوثائق مقدار تأثر حركة حسام.']],effectSource:'https://www.niams.nih.gov/health-topics/osteoarthritis'
  }
};
